CREATE DATABASE SQLTASK 

USE SQLTASK


CREATE TABLE EXAMPLETABLE 
(
	ID INT CONSTRAINT pk_EXAMPLETABLE PRIMARY KEY IDENTITY,
	NAME NVARCHAR(50)  CONSTRAINT df_EXAMPLETABLE_NAME DEFAULT 'N/A' ,
	SALARY MONEY CONSTRAINT df_EXAMPLETABLE_SALARY DEFAULT 0, 
	
)

ALTER TABLE EXAMPLETABLE DROP CONSTRAINT df_EXAMPLETABLE_NAME