CREATE TABLE DEPARTMENTS 
(
	ID INT PRIMARY KEY IDENTITY,
	NAME NVARCHAR(50) CHECK(LEN(NAME) > 2) NOT NULL

)







CREATE TABLE EMPLOYEES 
(
	ID INT PRIMARY KEY IDENTITY,
	FULLNAME NVARCHAR(50) NOT NULL CHECK(LEN(FULLNAME) > 3),
	SALARY MONEY CHECK(SALARY >= 0),
	EMAIL NVARCHAR(50) UNIQUE NOT NULL CHECK(EMAIL LIKE '%@%'),
	DEPARTMENTID INT FOREIGN KEY REFERENCES DEPARTMENTS(ID)
)

